# Generated by Django 4.2.6 on 2024-02-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_propertydb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydb',
            name='empdis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertydb',
            name='empimg',
            field=models.ImageField(blank=True, null=True, upload_to='proprofile'),
        ),
        migrations.AddField(
            model_name='propertydb',
            name='empmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertydb',
            name='empname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
