# Generated by Django 4.2.6 on 2024-02-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_propertydb_empdis_propertydb_empimg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydb',
            old_name='empimg',
            new_name='eimage',
        ),
        migrations.RenameField(
            model_name='propertydb',
            old_name='empdis',
            new_name='pdepartment',
        ),
        migrations.RenameField(
            model_name='propertydb',
            old_name='empmail',
            new_name='pediscription',
        ),
        migrations.RenameField(
            model_name='propertydb',
            old_name='empname',
            new_name='peemail',
        ),
    ]
