# Generated by Django 4.2.6 on 2024-02-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_rename_empimg_propertydb_eimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydb',
            old_name='pediscription',
            new_name='pediscriptiom',
        ),
    ]
