# Generated by Django 4.2.6 on 2024-02-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_rename_pediscription_propertydb_pediscriptiom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydb',
            old_name='pediscriptiom',
            new_name='pediscription',
        ),
    ]
