# Generated by Django 4.2.6 on 2024-02-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0011_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rmessage', models.CharField(blank=True, max_length=500, null=True)),
                ('ruser', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userinterestdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spuname', models.CharField(blank=True, max_length=50, null=True)),
                ('spemail', models.CharField(blank=True, max_length=50, null=True)),
                ('spunumber', models.CharField(blank=True, max_length=50, null=True)),
                ('spname', models.CharField(blank=True, max_length=50, null=True)),
                ('spaddress', models.CharField(blank=True, max_length=50, null=True)),
                ('spprice', models.CharField(blank=True, max_length=50, null=True)),
                ('speemail', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usernotificationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unemail', models.CharField(blank=True, max_length=50, null=True)),
                ('ununame', models.CharField(blank=True, max_length=50, null=True)),
                ('unemployee', models.CharField(blank=True, max_length=50, null=True)),
                ('unstype', models.CharField(blank=True, max_length=50, null=True)),
                ('unuemail', models.CharField(blank=True, max_length=50, null=True)),
                ('ununumber', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='useremployeedb',
            old_name='eusername',
            new_name='eemail',
        ),
        migrations.RemoveField(
            model_name='useremployeedb',
            name='uemail',
        ),
        migrations.AlterField(
            model_name='usersignupdb',
            name='uusername',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
